/* Auto-generated by genmsg_cpp for file /tmp/buildd/ros-groovy-pr2-object-manipulation-0.7.5/debian/ros-groovy-pr2-object-manipulation/opt/ros/groovy/stacks/pr2_object_manipulation/manipulation/pr2_gripper_sensor_msgs/msg/PR2GripperSensorRTState.msg */
#ifndef PR2_GRIPPER_SENSOR_MSGS_MESSAGE_PR2GRIPPERSENSORRTSTATE_H
#define PR2_GRIPPER_SENSOR_MSGS_MESSAGE_PR2GRIPPERSENSORRTSTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace pr2_gripper_sensor_msgs
{
template <class ContainerAllocator>
struct PR2GripperSensorRTState_ {
  typedef PR2GripperSensorRTState_<ContainerAllocator> Type;

  PR2GripperSensorRTState_()
  : realtime_controller_state(0)
  {
  }

  PR2GripperSensorRTState_(const ContainerAllocator& _alloc)
  : realtime_controller_state(0)
  {
  }

  typedef int8_t _realtime_controller_state_type;
  int8_t realtime_controller_state;

  enum { DISABLED = 0 };
  enum { POSITION_SERVO = 3 };
  enum { FORCE_SERVO = 4 };
  enum { FIND_CONTACT = 5 };
  enum { SLIP_SERVO = 6 };

  typedef boost::shared_ptr< ::pr2_gripper_sensor_msgs::PR2GripperSensorRTState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr2_gripper_sensor_msgs::PR2GripperSensorRTState_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PR2GripperSensorRTState
typedef  ::pr2_gripper_sensor_msgs::PR2GripperSensorRTState_<std::allocator<void> > PR2GripperSensorRTState;

typedef boost::shared_ptr< ::pr2_gripper_sensor_msgs::PR2GripperSensorRTState> PR2GripperSensorRTStatePtr;
typedef boost::shared_ptr< ::pr2_gripper_sensor_msgs::PR2GripperSensorRTState const> PR2GripperSensorRTStateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::pr2_gripper_sensor_msgs::PR2GripperSensorRTState_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::pr2_gripper_sensor_msgs::PR2GripperSensorRTState_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace pr2_gripper_sensor_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::pr2_gripper_sensor_msgs::PR2GripperSensorRTState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::pr2_gripper_sensor_msgs::PR2GripperSensorRTState_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::pr2_gripper_sensor_msgs::PR2GripperSensorRTState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8109436c1f7237c52c00d885ed5755d7";
  }

  static const char* value(const  ::pr2_gripper_sensor_msgs::PR2GripperSensorRTState_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x8109436c1f7237c5ULL;
  static const uint64_t static_value2 = 0x2c00d885ed5755d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr2_gripper_sensor_msgs::PR2GripperSensorRTState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pr2_gripper_sensor_msgs/PR2GripperSensorRTState";
  }

  static const char* value(const  ::pr2_gripper_sensor_msgs::PR2GripperSensorRTState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::pr2_gripper_sensor_msgs::PR2GripperSensorRTState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# the control state of our realtime controller\n\
int8 realtime_controller_state\n\
\n\
# predefined values to indicate our realtime_controller_state\n\
int8 DISABLED = 0\n\
int8 POSITION_SERVO = 3\n\
int8 FORCE_SERVO = 4\n\
int8 FIND_CONTACT = 5\n\
int8 SLIP_SERVO = 6\n\
";
  }

  static const char* value(const  ::pr2_gripper_sensor_msgs::PR2GripperSensorRTState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::pr2_gripper_sensor_msgs::PR2GripperSensorRTState_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::pr2_gripper_sensor_msgs::PR2GripperSensorRTState_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.realtime_controller_state);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PR2GripperSensorRTState_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr2_gripper_sensor_msgs::PR2GripperSensorRTState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::pr2_gripper_sensor_msgs::PR2GripperSensorRTState_<ContainerAllocator> & v) 
  {
    s << indent << "realtime_controller_state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.realtime_controller_state);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PR2_GRIPPER_SENSOR_MSGS_MESSAGE_PR2GRIPPERSENSORRTSTATE_H

