/* Auto-generated by genmsg_cpp for file /tmp/buildd/ros-groovy-pr2-object-manipulation-0.7.5/debian/ros-groovy-pr2-object-manipulation/opt/ros/groovy/stacks/pr2_object_manipulation/manipulation/pr2_gripper_sensor_msgs/msg/PR2GripperForceServoGoal.msg */
#ifndef PR2_GRIPPER_SENSOR_MSGS_MESSAGE_PR2GRIPPERFORCESERVOGOAL_H
#define PR2_GRIPPER_SENSOR_MSGS_MESSAGE_PR2GRIPPERFORCESERVOGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "pr2_gripper_sensor_msgs/PR2GripperForceServoCommand.h"

namespace pr2_gripper_sensor_msgs
{
template <class ContainerAllocator>
struct PR2GripperForceServoGoal_ {
  typedef PR2GripperForceServoGoal_<ContainerAllocator> Type;

  PR2GripperForceServoGoal_()
  : command()
  {
  }

  PR2GripperForceServoGoal_(const ContainerAllocator& _alloc)
  : command(_alloc)
  {
  }

  typedef  ::pr2_gripper_sensor_msgs::PR2GripperForceServoCommand_<ContainerAllocator>  _command_type;
   ::pr2_gripper_sensor_msgs::PR2GripperForceServoCommand_<ContainerAllocator>  command;


  typedef boost::shared_ptr< ::pr2_gripper_sensor_msgs::PR2GripperForceServoGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr2_gripper_sensor_msgs::PR2GripperForceServoGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PR2GripperForceServoGoal
typedef  ::pr2_gripper_sensor_msgs::PR2GripperForceServoGoal_<std::allocator<void> > PR2GripperForceServoGoal;

typedef boost::shared_ptr< ::pr2_gripper_sensor_msgs::PR2GripperForceServoGoal> PR2GripperForceServoGoalPtr;
typedef boost::shared_ptr< ::pr2_gripper_sensor_msgs::PR2GripperForceServoGoal const> PR2GripperForceServoGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::pr2_gripper_sensor_msgs::PR2GripperForceServoGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::pr2_gripper_sensor_msgs::PR2GripperForceServoGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace pr2_gripper_sensor_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::pr2_gripper_sensor_msgs::PR2GripperForceServoGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::pr2_gripper_sensor_msgs::PR2GripperForceServoGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::pr2_gripper_sensor_msgs::PR2GripperForceServoGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "72dfec6461d0f26a4433260fc791bc48";
  }

  static const char* value(const  ::pr2_gripper_sensor_msgs::PR2GripperForceServoGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x72dfec6461d0f26aULL;
  static const uint64_t static_value2 = 0x4433260fc791bc48ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr2_gripper_sensor_msgs::PR2GripperForceServoGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pr2_gripper_sensor_msgs/PR2GripperForceServoGoal";
  }

  static const char* value(const  ::pr2_gripper_sensor_msgs::PR2GripperForceServoGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::pr2_gripper_sensor_msgs::PR2GripperForceServoGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Action to launch the gripper into force servoing mode \n\
\n\
#goals\n\
PR2GripperForceServoCommand command\n\
\n\
================================================================================\n\
MSG: pr2_gripper_sensor_msgs/PR2GripperForceServoCommand\n\
# the amount of fingertip force (in Newtons) to apply.\n\
# NOTE: the joint will squeeze until each finger reaches this level\n\
# values < 0 (opening force) are ignored\n\
#\n\
# 10 N can crack an egg or crush a soda can.\n\
# 15 N can firmly pick up a can of soup.\n\
# Experiment on your own.\n\
#\n\
float64 fingertip_force\n\
";
  }

  static const char* value(const  ::pr2_gripper_sensor_msgs::PR2GripperForceServoGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::pr2_gripper_sensor_msgs::PR2GripperForceServoGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::pr2_gripper_sensor_msgs::PR2GripperForceServoGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.command);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PR2GripperForceServoGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr2_gripper_sensor_msgs::PR2GripperForceServoGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::pr2_gripper_sensor_msgs::PR2GripperForceServoGoal_<ContainerAllocator> & v) 
  {
    s << indent << "command: ";
s << std::endl;
    Printer< ::pr2_gripper_sensor_msgs::PR2GripperForceServoCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.command);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PR2_GRIPPER_SENSOR_MSGS_MESSAGE_PR2GRIPPERFORCESERVOGOAL_H

