/* Auto-generated by genmsg_cpp for file /tmp/buildd/ros-groovy-pr2-object-manipulation-0.7.5/debian/ros-groovy-pr2-object-manipulation/opt/ros/groovy/stacks/pr2_object_manipulation/manipulation/pr2_gripper_sensor_msgs/msg/PR2GripperFindContactData.msg */
#ifndef PR2_GRIPPER_SENSOR_MSGS_MESSAGE_PR2GRIPPERFINDCONTACTDATA_H
#define PR2_GRIPPER_SENSOR_MSGS_MESSAGE_PR2GRIPPERFINDCONTACTDATA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "pr2_gripper_sensor_msgs/PR2GripperSensorRTState.h"

namespace pr2_gripper_sensor_msgs
{
template <class ContainerAllocator>
struct PR2GripperFindContactData_ {
  typedef PR2GripperFindContactData_<ContainerAllocator> Type;

  PR2GripperFindContactData_()
  : stamp()
  , contact_conditions_met(false)
  , left_fingertip_pad_contact(false)
  , right_fingertip_pad_contact(false)
  , left_fingertip_pad_force(0.0)
  , right_fingertip_pad_force(0.0)
  , joint_position(0.0)
  , joint_effort(0.0)
  , rtstate()
  {
  }

  PR2GripperFindContactData_(const ContainerAllocator& _alloc)
  : stamp()
  , contact_conditions_met(false)
  , left_fingertip_pad_contact(false)
  , right_fingertip_pad_contact(false)
  , left_fingertip_pad_force(0.0)
  , right_fingertip_pad_force(0.0)
  , joint_position(0.0)
  , joint_effort(0.0)
  , rtstate(_alloc)
  {
  }

  typedef ros::Time _stamp_type;
  ros::Time stamp;

  typedef uint8_t _contact_conditions_met_type;
  uint8_t contact_conditions_met;

  typedef uint8_t _left_fingertip_pad_contact_type;
  uint8_t left_fingertip_pad_contact;

  typedef uint8_t _right_fingertip_pad_contact_type;
  uint8_t right_fingertip_pad_contact;

  typedef double _left_fingertip_pad_force_type;
  double left_fingertip_pad_force;

  typedef double _right_fingertip_pad_force_type;
  double right_fingertip_pad_force;

  typedef double _joint_position_type;
  double joint_position;

  typedef double _joint_effort_type;
  double joint_effort;

  typedef  ::pr2_gripper_sensor_msgs::PR2GripperSensorRTState_<ContainerAllocator>  _rtstate_type;
   ::pr2_gripper_sensor_msgs::PR2GripperSensorRTState_<ContainerAllocator>  rtstate;


  typedef boost::shared_ptr< ::pr2_gripper_sensor_msgs::PR2GripperFindContactData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr2_gripper_sensor_msgs::PR2GripperFindContactData_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PR2GripperFindContactData
typedef  ::pr2_gripper_sensor_msgs::PR2GripperFindContactData_<std::allocator<void> > PR2GripperFindContactData;

typedef boost::shared_ptr< ::pr2_gripper_sensor_msgs::PR2GripperFindContactData> PR2GripperFindContactDataPtr;
typedef boost::shared_ptr< ::pr2_gripper_sensor_msgs::PR2GripperFindContactData const> PR2GripperFindContactDataConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::pr2_gripper_sensor_msgs::PR2GripperFindContactData_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::pr2_gripper_sensor_msgs::PR2GripperFindContactData_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace pr2_gripper_sensor_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::pr2_gripper_sensor_msgs::PR2GripperFindContactData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::pr2_gripper_sensor_msgs::PR2GripperFindContactData_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::pr2_gripper_sensor_msgs::PR2GripperFindContactData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bc53e3dc7d19b896ca9b5ea205d54b91";
  }

  static const char* value(const  ::pr2_gripper_sensor_msgs::PR2GripperFindContactData_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xbc53e3dc7d19b896ULL;
  static const uint64_t static_value2 = 0xca9b5ea205d54b91ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr2_gripper_sensor_msgs::PR2GripperFindContactData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pr2_gripper_sensor_msgs/PR2GripperFindContactData";
  }

  static const char* value(const  ::pr2_gripper_sensor_msgs::PR2GripperFindContactData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::pr2_gripper_sensor_msgs::PR2GripperFindContactData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Time the data was recorded at\n\
time stamp\n\
\n\
# true when our contact conditions have been met\n\
# (see PR2GripperFindContact command)\n\
bool contact_conditions_met\n\
\n\
# the finger contact conditions \n\
# true if the finger experienced a contact event\n\
#\n\
# contact events are defined as contact with the fingerpads\n\
# as either steady-state or high-freq force events\n\
bool left_fingertip_pad_contact\n\
bool right_fingertip_pad_contact\n\
\n\
# the force experinced by the finger Pads  (N)\n\
# NOTE:this ignores data from the edges of the finger pressure\n\
float64 left_fingertip_pad_force\n\
float64 right_fingertip_pad_force\n\
\n\
# the current joint position (m)\n\
float64 joint_position\n\
\n\
# the virtual (parallel) joint effort (N)\n\
float64 joint_effort\n\
\n\
# the control state of our realtime controller\n\
PR2GripperSensorRTState rtstate\n\
================================================================================\n\
MSG: pr2_gripper_sensor_msgs/PR2GripperSensorRTState\n\
# the control state of our realtime controller\n\
int8 realtime_controller_state\n\
\n\
# predefined values to indicate our realtime_controller_state\n\
int8 DISABLED = 0\n\
int8 POSITION_SERVO = 3\n\
int8 FORCE_SERVO = 4\n\
int8 FIND_CONTACT = 5\n\
int8 SLIP_SERVO = 6\n\
";
  }

  static const char* value(const  ::pr2_gripper_sensor_msgs::PR2GripperFindContactData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::pr2_gripper_sensor_msgs::PR2GripperFindContactData_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::pr2_gripper_sensor_msgs::PR2GripperFindContactData_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.stamp);
    stream.next(m.contact_conditions_met);
    stream.next(m.left_fingertip_pad_contact);
    stream.next(m.right_fingertip_pad_contact);
    stream.next(m.left_fingertip_pad_force);
    stream.next(m.right_fingertip_pad_force);
    stream.next(m.joint_position);
    stream.next(m.joint_effort);
    stream.next(m.rtstate);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PR2GripperFindContactData_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr2_gripper_sensor_msgs::PR2GripperFindContactData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::pr2_gripper_sensor_msgs::PR2GripperFindContactData_<ContainerAllocator> & v) 
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "contact_conditions_met: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.contact_conditions_met);
    s << indent << "left_fingertip_pad_contact: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_fingertip_pad_contact);
    s << indent << "right_fingertip_pad_contact: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_fingertip_pad_contact);
    s << indent << "left_fingertip_pad_force: ";
    Printer<double>::stream(s, indent + "  ", v.left_fingertip_pad_force);
    s << indent << "right_fingertip_pad_force: ";
    Printer<double>::stream(s, indent + "  ", v.right_fingertip_pad_force);
    s << indent << "joint_position: ";
    Printer<double>::stream(s, indent + "  ", v.joint_position);
    s << indent << "joint_effort: ";
    Printer<double>::stream(s, indent + "  ", v.joint_effort);
    s << indent << "rtstate: ";
s << std::endl;
    Printer< ::pr2_gripper_sensor_msgs::PR2GripperSensorRTState_<ContainerAllocator> >::stream(s, indent + "  ", v.rtstate);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PR2_GRIPPER_SENSOR_MSGS_MESSAGE_PR2GRIPPERFINDCONTACTDATA_H

