/* Auto-generated by genmsg_cpp for file /tmp/buildd/ros-groovy-pr2-object-manipulation-0.7.5/debian/ros-groovy-pr2-object-manipulation/opt/ros/groovy/stacks/pr2_object_manipulation/manipulation/pr2_gripper_sensor_msgs/msg/PR2GripperSlipServoGoal.msg */
#ifndef PR2_GRIPPER_SENSOR_MSGS_MESSAGE_PR2GRIPPERSLIPSERVOGOAL_H
#define PR2_GRIPPER_SENSOR_MSGS_MESSAGE_PR2GRIPPERSLIPSERVOGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "pr2_gripper_sensor_msgs/PR2GripperSlipServoCommand.h"

namespace pr2_gripper_sensor_msgs
{
template <class ContainerAllocator>
struct PR2GripperSlipServoGoal_ {
  typedef PR2GripperSlipServoGoal_<ContainerAllocator> Type;

  PR2GripperSlipServoGoal_()
  : command()
  {
  }

  PR2GripperSlipServoGoal_(const ContainerAllocator& _alloc)
  : command(_alloc)
  {
  }

  typedef  ::pr2_gripper_sensor_msgs::PR2GripperSlipServoCommand_<ContainerAllocator>  _command_type;
   ::pr2_gripper_sensor_msgs::PR2GripperSlipServoCommand_<ContainerAllocator>  command;


  typedef boost::shared_ptr< ::pr2_gripper_sensor_msgs::PR2GripperSlipServoGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr2_gripper_sensor_msgs::PR2GripperSlipServoGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PR2GripperSlipServoGoal
typedef  ::pr2_gripper_sensor_msgs::PR2GripperSlipServoGoal_<std::allocator<void> > PR2GripperSlipServoGoal;

typedef boost::shared_ptr< ::pr2_gripper_sensor_msgs::PR2GripperSlipServoGoal> PR2GripperSlipServoGoalPtr;
typedef boost::shared_ptr< ::pr2_gripper_sensor_msgs::PR2GripperSlipServoGoal const> PR2GripperSlipServoGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::pr2_gripper_sensor_msgs::PR2GripperSlipServoGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::pr2_gripper_sensor_msgs::PR2GripperSlipServoGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace pr2_gripper_sensor_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::pr2_gripper_sensor_msgs::PR2GripperSlipServoGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::pr2_gripper_sensor_msgs::PR2GripperSlipServoGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::pr2_gripper_sensor_msgs::PR2GripperSlipServoGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bf76e656d304158c04ab279db7cefc85";
  }

  static const char* value(const  ::pr2_gripper_sensor_msgs::PR2GripperSlipServoGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xbf76e656d304158cULL;
  static const uint64_t static_value2 = 0x04ab279db7cefc85ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr2_gripper_sensor_msgs::PR2GripperSlipServoGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pr2_gripper_sensor_msgs/PR2GripperSlipServoGoal";
  }

  static const char* value(const  ::pr2_gripper_sensor_msgs::PR2GripperSlipServoGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::pr2_gripper_sensor_msgs::PR2GripperSlipServoGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Action to launch the gripper into slip servoing mode \n\
\n\
#goals\n\
PR2GripperSlipServoCommand command\n\
\n\
================================================================================\n\
MSG: pr2_gripper_sensor_msgs/PR2GripperSlipServoCommand\n\
# this command is currently blank, but may see additional variable\n\
# additions in the future\n\
\n\
# see the param server documentation for a list of variables that effect\n\
# slip servo performance\n\
";
  }

  static const char* value(const  ::pr2_gripper_sensor_msgs::PR2GripperSlipServoGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::pr2_gripper_sensor_msgs::PR2GripperSlipServoGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::pr2_gripper_sensor_msgs::PR2GripperSlipServoGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.command);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PR2GripperSlipServoGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr2_gripper_sensor_msgs::PR2GripperSlipServoGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::pr2_gripper_sensor_msgs::PR2GripperSlipServoGoal_<ContainerAllocator> & v) 
  {
    s << indent << "command: ";
s << std::endl;
    Printer< ::pr2_gripper_sensor_msgs::PR2GripperSlipServoCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.command);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PR2_GRIPPER_SENSOR_MSGS_MESSAGE_PR2GRIPPERSLIPSERVOGOAL_H

