#right arm
string RIGHT_ARM="right_arm"
string LEFT_ARM="left_arm"
string HEAD="head"

#goal definition
suturo_perception_msgs/PerceivedObject p
string arm
---
#result definition
ActionAnswer succ
---
#feedback
int32[] sequence
